#!/bin/sh

TOOLSET=gcc

echo -n "Building Boost.Jam with toolset $TOOLSET..."
pwd=`pwd`
cd "tools/jam/src" && ./build.sh "$TOOLSET" > config.log 2>&1
cd $pwd
arch=`cd tools/jam/src && ./bootstrap/jam0 -d0 -f build.jam --toolset=$TOOLSET --toolset-root= --show-locate-target && cd ..`
BJAM="tools/jam/src/$arch/bjam"
cp $BJAM ./bin

echo ""

cat > user-config.jam <<EOF
#Automatically generated by buildtools.sh

using $TOOLSET ;

EOF
